class Temp{
	public static void main(String[] celsius)
	{
		System.out.println("Distance from Bengaluru");
		double temperature=1;
		{
		if(temperature==1);
		{
		System.out.println("Jammu & Kashmir");
		}
		}
		{
		if(temperature==2);
		System.out.println("Tamilnadu");
		}		
		{
		if(temperature==3);
		System.out.println("Kerala");	
		}
		{
		if(temperature==3);
		System.out.println("Assam");
		}
		{
		if(temperature==4);
		System.out.println("Bihar");
		distanceFromBengaluru=2900;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==5);
		System.out.println("Goa");
		distanceFromBengaluru=3000;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==6);
		System.out.println("Haryana");
		distanceFromBengaluru=3100;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==7);
		System.out.println("Himachal Pradesh");
		distanceFromBengaluru=3200;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==8);
		System.out.println("Jharkand");
		distanceFromBengaluru=3300;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==9);
		System.out.println("Madhya Pradesh");
		distanceFromBengaluru=3400;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==10);
		System.out.println("Maharashtra");
		distanceFromBengaluru=3500;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==11);
		System.out.println("Manipur");
		distanceFromBengaluru=3600;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==12);
		System.out.println("Meghalaya");
		distanceFromBengaluru=3700;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==13);
		System.out.println("Mizoram");
		distanceFromBengaluru=3800;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==14);
		System.out.println("Nagaland");
		distanceFromBengaluru=3900;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==15);
		System.out.println("Odisha");
		distanceFromBengaluru=4000;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==16);
		System.out.println("Punjab");
		distanceFromBengaluru=4100;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==17);
		System.out.println("Rajasthan");
		distanceFromBengaluru=4200;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==18);
		System.out.println("Sikkim");
		distanceFromBengaluru=4300;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==19);
		System.out.println("Telangana");
		distanceFromBengaluru=4400;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==20);
		System.out.println("Tripura");
		distanceFromBengaluru=4500;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==21);
		System.out.println("Uttarkhand");
		distanceFromBengaluru=4600;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==22);
		System.out.println("UttarPradesh");
		distanceFromBengaluru=4700;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==23);
		System.out.println("WestBengal");
		distanceFromBengaluru=4800;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==24);
		System.out.println("Puducherry");
		distanceFromBengaluru=5000;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==25);
		System.out.println("ArunachalPradesh");
		distanceFromBengaluru=5100;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==26);
		System.out.println("lakshadweep");
		distanceFromBengaluru=5200;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
		{
		if(temperature==27);
		System.out.println("Ladakh");
		distanceFromBengaluru=5300;	
		}
		{
		System.out.println("DistanceFromBengaluru:"+distanceFromBengaluru);
		}
	}
}
